apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "harbor.fullname" . }}-jobservice"
  namespace: {{ .Release.Namespace | quote }}
  labels:
{{ include "harbor.labels" . | indent 4 }}
type: Opaque
data:
  secret: {{ randAlphaNum 16 | b64enc | quote }}
  config.yml: |
{{ include "jobservice.config.yaml" . | b64enc | indent 4 }}