{{ if .Values.notary.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "harbor.fullname" . }}-notary
  namespace: {{ .Release.Namespace | quote }}
  labels:
{{ include "harbor.labels" . | indent 4 }}
    component: notary
type: Opaque
data:
  DB_URL_server: {{ include "harbor.database.notaryServer" . | b64enc }}
  DB_URL_signer: {{ include "harbor.database.notarySigner" . | b64enc }}
  server-config.postgres.json: {{ include "server-config.postgres.json" . | b64enc }}
  signer-config.postgres.json: {{ include "signer-config.postgres.json" . | b64enc }}
{{ end }}
