{{ if .Values.clair.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "harbor.fullname" . }}-clair
  namespace: {{ .Release.Namespace | quote }}
  labels:
{{ include "harbor.labels" . | indent 4 }}
    component: clair
type: Opaque
data:
  config.yaml: {{ include "clair.config.yaml" . | b64enc }}
{{ end }}
