apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "harbor.fullname" . }}-adminserver"
  namespace: {{ .Release.Namespace | quote }}  
  labels:
{{ include "harbor.labels" . | indent 4 }}
    component: adminserver
type: Opaque
data:
  secretKey: {{ .Values.secretKey | b64enc | quote }}
  HARBOR_ADMIN_PASSWORD: {{ .Values.harborAdminPassword | b64enc | quote }}
  POSTGRESQL_PASSWORD: {{ template "harbor.database.password" . }}
  POSTGRESQL_USERNAME: {{ template "harbor.database.username" . }}
{{ if .Values.clair.enabled }}
  CLAIR_DB_PASSWORD: {{ template "harbor.database.password" . }}
  CLAIR_DB_USERNAME: {{ template "harbor.database.username" . }}
{{ end }}
